In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
fifa = pd.read_csv('data.csv')
fifa.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [3]:
# Extracting Features
features = ['Age','Club', 'Nationality', 'Preferred Foot', 'Overall', 
          'Potential','Special', 'International Reputation','Weak Foot', 'Skill Moves',
          'Crossing', 'Finishing', 'HeadingAccuracy',
          'ShortPassing', 'Volleys','Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 
          'BallControl','Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
          'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
          'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
          'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
          'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes', 'Value', 'Release Clause']

fifa = fifa[features]
fifa.head()

,Age,Club,Nationality,Preferred Foot,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Value,Release Clause
0,31,FC Barcelona,Argentina,Left,94,94,2202,5.0,4.0,4.0,...,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€110.5M,€226.5M
1,33,Juventus,Portugal,Right,94,94,2228,5.0,4.0,5.0,...,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€77M,€127.1M
2,26,Paris Saint-Germain,Brazil,Right,92,93,2143,5.0,5.0,5.0,...,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€118.5M,€228.1M
3,27,Manchester United,Spain,Right,91,93,1471,4.0,3.0,1.0,...,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€72M,€138.6M
4,27,Manchester City,Belgium,Right,91,92,2281,4.0,5.0,4.0,...,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€102M,€196.4M

In [4]:
fifa.shape

(18207, 46)

# Simple Position

In [5]:
fifa.isnull().sum()

Age                            0
Club                         241
Nationality                    0
Preferred Foot                48
Overall                        0
Potential                      0
Special                        0
International Reputation      48
Weak Foot                     48
Skill Moves                   48
Crossing                      48
Finishing                     48
HeadingAccuracy               48
ShortPassing                  48
Volleys                       48
Dribbling                     48
Curve                         48
FKAccuracy                    48
LongPassing                   48
BallControl                   48
Acceleration                  48
SprintSpeed                   48
Agility                       48
Reactions                     48
Balance                       48
ShotPower                     48
Jumping                       48
Stamina                       48
Strength                      48
LongShots                     48
Aggression                    48
Interceptions                 48
Positioning                   48
Vision                        48
Penalties                     48
Composure                     48
Marking                       48
StandingTackle                48
SlidingTackle                 48
GKDiving                      48
GKHandling                    48
GKKicking                     48
GKPositioning                 48
GKReflexes                    48
Value                          0
Release Clause              1564
dtype: int64

In [6]:
fifa = fifa.dropna(subset=['Release Clause'])
fifa.isnull().sum()

Age                         0
Club                        0
Nationality                 0
Preferred Foot              0
Overall                     0
Potential                   0
Special                     0
International Reputation    0
Weak Foot                   0
Skill Moves                 0
Crossing                    0
Finishing                   0
HeadingAccuracy             0
ShortPassing                0
Volleys                     0
Dribbling                   0
Curve                       0
FKAccuracy                  0
LongPassing                 0
BallControl                 0
Acceleration                0
SprintSpeed                 0
Agility                     0
Reactions                   0
Balance                     0
ShotPower                   0
Jumping                     0
Stamina                     0
Strength                    0
LongShots                   0
Aggression                  0
Interceptions               0
Positioning                 0
Vision                      0
Penalties                   0
Composure                   0
Marking                     0
StandingTackle              0
SlidingTackle               0
GKDiving                    0
GKHandling                  0
GKKicking                   0
GKPositioning               0
GKReflexes                  0
Value                       0
Release Clause              0
dtype: int64

# Clean Currency

In [7]:
def clean_currency(val):
    if isinstance(val, str):
        val = val.replace('€', '')
        if 'M' in val:
            val = val.replace('M', '')
            val = float(val) * 1000000
    
        elif 'K' in val:
            val = val.replace('K', '')
            val = float(val) * 1000
                
    return(val)

In [8]:
#fifa['Value in M€'] = fifa['Value'].apply(clean_currency)
fifa['Release Clause in M€'] = fifa['Release Clause'].apply(clean_currency)
fifa['Value in K€'] = (fifa['Value'].apply(clean_currency).astype(float)).astype(int)
fifa = fifa.drop(['Value', 'Release Clause'], axis=1)
fifa.head()

,Age,Club,Nationality,Preferred Foot,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause in M€,Value in K€
0,31,FC Barcelona,Argentina,Left,94,94,2202,5.0,4.0,4.0,...,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0,110500000
1,33,Juventus,Portugal,Right,94,94,2228,5.0,4.0,5.0,...,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0,77000000
2,26,Paris Saint-Germain,Brazil,Right,92,93,2143,5.0,5.0,5.0,...,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0,118500000
3,27,Manchester United,Spain,Right,91,93,1471,4.0,3.0,1.0,...,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138600000.0,72000000
4,27,Manchester City,Belgium,Right,91,92,2281,4.0,5.0,4.0,...,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0,102000000

In [9]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16643 entries, 0 to 18206
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       16643 non-null  int64
 1   Club                      16643 non-null  object
 2   Nationality               16643 non-null  object
 3   Preferred Foot            16643 non-null  object
 4   Overall                   16643 non-null  int64
 5   Potential                 16643 non-null  int64
 6   Special                   16643 non-null  int64
 7   International Reputation  16643 non-null  float64
 8   Weak Foot                 16643 non-null  float64
 9   Skill Moves               16643 non-null  float64
 10  Crossing                  16643 non-null  float64
 11  Finishing                 16643 non-null  float64
 12  HeadingAccuracy           16643 non-null  float64
 13  ShortPassing              16643 non-null  float64
 14  Volleys                   16643 non-null  float64
 15  Dribbling                 16643 non-null  float64
 16  Curve                     16643 non-null  float64
 17  FKAccuracy                16643 non-null  float64
 18  LongPassing               16643 non-null  float64
 19  BallControl               16643 non-null  float64
 20  Acceleration              16643 non-null  float64
 21  SprintSpeed               16643 non-null  float64
 22  Agility                   16643 non-null  float64
 23  Reactions                 16643 non-null  float64
 24  Balance                   16643 non-null  float64
 25  ShotPower                 16643 non-null  float64
 26  Jumping                   16643 non-null  float64
 27  Stamina                   16643 non-null  float64
 28  Strength                  16643 non-null  float64
 29  LongShots                 16643 non-null  float64
 30  Aggression                16643 non-null  float64
 31  Interceptions             16643 non-null  float64
 32  Positioning               16643 non-null  float64
 33  Vision                    16643 non-null  float64
 34  Penalties                 16643 non-null  float64
 35  Composure                 16643 non-null  float64
 36  Marking                   16643 non-null  float64
 37  StandingTackle            16643 non-null  float64
 38  SlidingTackle             16643 non-null  float64
 39  GKDiving                  16643 non-null  float64
 40  GKHandling                16643 non-null  float64
 41  GKKicking                 16643 non-null  float64
 42  GKPositioning             16643 non-null  float64
 43  GKReflexes                16643 non-null  float64
 44  Release Clause in M€      16643 non-null  float64
 45  Value in K€               16643 non-null  int32
dtypes: float64(38), int32(1), int64(4), object(3)
memory usage: 5.9+ MB

# Converts Joind and Contract Valid Until to datetime format to get year

fifa['Joined'] = (pd.DatetimeIndex(fifa['Joined']).year)
fifa['Joined'] = fifa['Joined'].astype(pd.Int64Dtype())

fifa['Contract Valid Until'] = (pd.DatetimeIndex(fifa['Contract Valid Until']).year)
fifa['Contract Valid Until'] = fifa['Contract Valid Until'].astype(pd.Int64Dtype())

# Convert Height from feet inches to cm

def feet_to_cm(s):
    cm = 0
    if isinstance(s, str):
        s = s.replace("'", '')
        s1 = s[1:]
        s1 = float(s1)
        s2 = s[0]
        s2 = float(s2)
        cm = s1 + s2 * 12
        cm = round(cm * 2.54)
    return cm

fifa['Height'] = (fifa['Height'].apply(feet_to_cm).astype(float)).astype(int)
fifa.head()

# Convert Weight from bounds to Kilogramms

def bound_to_kg(s):
    kg = 0
    if isinstance(s, str):
        s = s.replace("lbs", '')
        kg = float(s)
        kg = round(kg * 0.453592)
    return kg

fifa['Weight'] = (fifa['Weight'].apply(bound_to_kg).astype(float)).astype(int)
fifa.head()

# Convert all of player's features from float to int type

In [10]:
for col in fifa.columns[5:-2]:
    fifa[col] = fifa[col].astype("int64")
    
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16643 entries, 0 to 18206
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       16643 non-null  int64
 1   Club                      16643 non-null  object
 2   Nationality               16643 non-null  object
 3   Preferred Foot            16643 non-null  object
 4   Overall                   16643 non-null  int64
 5   Potential                 16643 non-null  int64
 6   Special                   16643 non-null  int64
 7   International Reputation  16643 non-null  int64
 8   Weak Foot                 16643 non-null  int64
 9   Skill Moves               16643 non-null  int64
 10  Crossing                  16643 non-null  int64
 11  Finishing                 16643 non-null  int64
 12  HeadingAccuracy           16643 non-null  int64
 13  ShortPassing              16643 non-null  int64
 14  Volleys                   16643 non-null  int64
 15  Dribbling                 16643 non-null  int64
 16  Curve                     16643 non-null  int64
 17  FKAccuracy                16643 non-null  int64
 18  LongPassing               16643 non-null  int64
 19  BallControl               16643 non-null  int64
 20  Acceleration              16643 non-null  int64
 21  SprintSpeed               16643 non-null  int64
 22  Agility                   16643 non-null  int64
 23  Reactions                 16643 non-null  int64
 24  Balance                   16643 non-null  int64
 25  ShotPower                 16643 non-null  int64
 26  Jumping                   16643 non-null  int64
 27  Stamina                   16643 non-null  int64
 28  Strength                  16643 non-null  int64
 29  LongShots                 16643 non-null  int64
 30  Aggression                16643 non-null  int64
 31  Interceptions             16643 non-null  int64
 32  Positioning               16643 non-null  int64
 33  Vision                    16643 non-null  int64
 34  Penalties                 16643 non-null  int64
 35  Composure                 16643 non-null  int64
 36  Marking                   16643 non-null  int64
 37  StandingTackle            16643 non-null  int64
 38  SlidingTackle             16643 non-null  int64
 39  GKDiving                  16643 non-null  int64
 40  GKHandling                16643 non-null  int64
 41  GKKicking                 16643 non-null  int64
 42  GKPositioning             16643 non-null  int64
 43  GKReflexes                16643 non-null  int64
 44  Release Clause in M€      16643 non-null  float64
 45  Value in K€               16643 non-null  int32
dtypes: float64(1), int32(1), int64(41), object(3)
memory usage: 5.9+ MB

# Convert text and datetime into numeric values

In [11]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
columns = ['Club', 'Nationality', 'Preferred Foot']
def encode(cols):
    for i in cols:
        fifa[i] = enc.fit_transform(fifa[i].astype('str'))
        
encode(columns)
fifa.head()

,Age,Club,Nationality,Preferred Foot,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause in M€,Value in K€
0,31,212,6,0,94,94,2202,5,4,4,...,33,28,26,6,11,15,14,8,226500000.0,110500000
1,33,326,121,1,94,94,2228,5,4,5,...,28,31,23,7,11,15,14,11,127100000.0,77000000
2,26,435,20,1,92,93,2143,5,5,5,...,27,24,33,9,9,15,15,11,228100000.0,118500000
3,27,375,137,1,91,93,1471,4,3,1,...,15,21,13,90,85,87,88,94,138600000.0,72000000
4,27,374,13,1,91,92,2281,4,5,4,...,68,58,51,15,13,5,10,13,196400000.0,102000000

# Splitting dataset

In [12]:
X = fifa.drop('Value in K€', axis=1)
Y = fifa['Value in K€']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(13314, 45) (3329, 45) (13314,) (3329,)

# Linear Regression

In [14]:
from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

LinearRegression()

In [15]:
pred1 = np.around(lin_model.predict(X_test)).astype(int)

In [16]:
lin_model.score(X_test, Y_test)

0.9890377222785096